from typing import Type, TypeVar, Sequence, Optional, Any, overload

_T = TypeVar("_T")

class array:
    @overload
    @classmethod
    def __class_getitem__(cls, item: Type[_T]) -> type[Sequence[_T]]: ...
    @overload
    @classmethod
    def __class_getitem__(cls, item: tuple[Type[_T], int]) -> type[Sequence[_T]]: ...

    def __init__(self, subtype: type, length: int) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...


class sequence:
    @overload
    @classmethod
    def __class_getitem__(cls, item: Type[_T]) -> type[Sequence[_T]]: ...
    @overload
    @classmethod
    def __class_getitem__(cls, item: tuple[Type[_T], int]) -> type[Sequence[_T]]: ...

    def __init__(self, subtype: type, max_length: Optional[int] = None) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...


class typedef:
    @overload
    @classmethod
    def __class_getitem__(cls, item: tuple[str, Type[_T]]) -> type[_T]: ...
    @overload
    @classmethod
    def __class_getitem__(cls, item: Type[_T]) -> type[_T]: ...

    def __init__(self, name: str, subtype: type) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __call__(self, *args: Any, **kwds: Any) -> Any: ...
    @property
    def __idl_typename__(self) -> str: ...


class bounded_str:
    @overload
    @classmethod
    def __class_getitem__(cls, item: int) -> type[str]: ...

    def __init__(self, max_length: int) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...


class ValidUnionHolder:
    pass


class case(ValidUnionHolder):
    @overload
    @classmethod
    def __class_getitem__(cls, item: tuple[int, Type[_T]]) -> type[Optional[_T]]: ...
    @overload
    @classmethod
    def __class_getitem__(cls, item: Type[_T]) -> type[Optional[_T]]: ...

    def __init__(self, discriminator_value: int | list[int], subtype: type) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...


class default(ValidUnionHolder):
    @overload
    @classmethod
    def __class_getitem__(cls, item: Type[_T]) -> type[Optional[_T]]: ...

    def __init__(self, subtype: type) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, o: object) -> bool: ...
    def __hash__(self) -> int: ...


# IDL primitive type aliases
char = str
wchar = int
int8 = int
int16 = int
int32 = int
int64 = int
uint8 = int
uint16 = int
uint32 = int
uint64 = int
float32 = float
float64 = float

NoneType = type