#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

#
# Azure Pipeline specifically for building and publishing documentation
#

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - 'master'
    - 'releases/*'
pr: none

pool:
  vmImage: ubuntu-20.04

steps:
  - task: UsePythonVersion@0
    name: install_python
    displayName: Install Python
  - bash: |
      echo "###vso[task.setvariable variable=pip_cache;]$(pip cache dir)"
    displayName: Obtain pip cache path
  - task: Cache@2
    inputs:
      key: pip-docs | 4 | $(Agent.OS)
      path: $(pip_cache)
    name: cache_pip
    displayName: Retrieve pip cache
  - bash: |
      set -e -x
      cd docs
      pip install --user --upgrade pip
      pip install --user --upgrade -r requirements.txt
    name: install_sphinx
    displayName: Install Python dependencies
  - bash: |
      set -e -x
      cd docs
      mkdir build
      sphinx-build -b html -j auto -v ./source ./build
    name: run_sphinx
    displayName: Run Sphinx
  - bash: |
      set -e -x
      if [ "${BUILD_SOURCEBRANCHNAME}" = "master" ]; then
        version="latest"
      else
        version="$(echo ${BUILD_SOURCEBRANCHNAME} | sed -n -E 's#^.*[vV]?([0-9]+\.[0-9]+)\.[0-9]+((alpha|beta|rc)[0-9]*)?$#\1#p')"
      fi
      [ "${version}" != "" ] || exit 1
      echo "###vso[task.setvariable variable=version;]${version}"
    name: figure_version
    displayName: Compute documentation version
  - task: PublishBuildArtifacts@1
    displayName: Publish documentation artifact
    inputs:
      pathToPublish: docs/build
      artifactName: 'cyclonedds-python-docs-$(version)'