#
# Copyright(c) 2021 ADLINK Technology Limited and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

trigger: [ '*' ]

jobs:
- job: BuildCyclone
  pool:
    vmImage: $(image)
  strategy:
    matrix:
      'Ubuntu 20.04 LTS':
        image: ubuntu-20.04
      'macOS 10.15':
        image: macOS-10.15
      'Windows Server 2019':
        image: windows-2019
  steps:
  - template: /.azure/templates/build-wheel.yml