"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.9.0
  Module: vehicles
  IDL file: vehicle.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import vehicles


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Vehicle(idl.IdlStruct, typename="vehicles.Vehicle"):
    name: str
    x: types.int64
    y: types.int64


