"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.9.0
  Module: vehicles
  Entity: Vehicle

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

import vehicles
from . import __idl_module__

@dataclass
@annotate.final
@annotate.autoid("sequential")
class Vehicle(idl.IdlStruct, typename="vehicles.Vehicle"):
    name: str
    x: types.int64
    y: types.int64
